#!/bin/python
# -*- coding: utf-8 -*-

import requests

CITY = "2988507"
API_KEY = "8deac06554aa8d2f14983e8a9e309ebe"
UNITS = "metric"
UNIT_KEY = "c"

REQ = requests.get("http://api.openweathermap.org/data/2.5/weather?id=2988507&appid=8deac06554aa8d2f14983e8a9e309ebe&units=metric&lang=fr".format(CITY, API_KEY, UNITS))
try:
    # HTTP CODE = OK
    if REQ.status_code == 200:
        CURRENT = REQ.json()["weather"][0]["description"].capitalize()
        TEMP = int(float(REQ.json()["main"]["temp"]))
        # Rajoute CURRENT devant TEMP
        print("{}, {}°{}".format(CURRENT, TEMP, UNIT_KEY))
    else:
        print("Error: BAD HTTP STATUS CODE " + str(REQ.status_code))
except (ValueError, IOError):
    print("Error: Unable print the data")